development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 20
  timeout: 1500

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

world:
  adapter: sqlite3
  database: db/world.sqlite3
  pool: 5
  timeout: 5000
